src/ws-egl.cpp: add missing unistd.h header
This addresses build failures with musl:

| ../../../../../../workspace/sources/wpebackend-fdo/src/ws-egl.cpp: In destructor 'virtual WS::ImplEGL::~ImplEGL()':
| ../../../../../../workspace/sources/wpebackend-fdo/src/ws-egl.cpp:83:9: error: 'close' was not declared in this scope; did you mean 'clone'?
|    83 |         close(m_dmabuf.formatTable.fd);
|       |         ^~~~~
|       |         clone
| ../../../../../../workspace/sources/wpebackend-fdo/src/ws-egl.cpp: In member function 'void WS::ImplEGL::initFormatTable()':
| ../../../../../../workspace/sources/wpebackend-fdo/src/ws-egl.cpp:397:15: error: 'ftruncate' was not declared in this scope; did you mean 'strncat'?
|   397 |         ret = ftruncate(fd, size);
|       |               ^~~~~~~~~
|       |               strncat

Signed-off-by: Alexander Kanavin <alex@linutronix.de>