src/ipc.h: Include <stdint.h> for uint32_t
Without this the build fails with the upcoming gcc 15:

In file included from ../wpebackend-fdo-1.14.2/src/ipc.cpp:26:
../wpebackend-fdo-1.14.2/src/ipc.h:36:36: error: 'uint32_t' has not been declared
   36 |     virtual void didReceiveMessage(uint32_t messageId, uint32_t messageBody) = 0

(cherry picked from commit 923ebd634949c11444fbdb6b1ee9ac62ac538ec7)