version: Expose version retrieval functions
Otherwise client code relying on it will not compile (undefined reference to
`wpe_fdo_get_minor_version', etc).

(cherry picked from commit 1f58ebdf632fdf90f691949d90c8338a8d7073c7)